apiVersion: v1
kind: Pod

metadata:
  name: spring-boot-pod
  labels:
    app: springWeb

spec:
  containers:
    - name: spring-boot-k8s
      image: subhendugn/spring-boot-k8s:v1
      ports:
        - containerPort: 8070
    